// <auto-generated />
using System;
using System.Collections.Generic;
using MedConnect.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedConnect.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MedConnectDbContext))]
    partial class MedConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MedConnect.Domain.Entities.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActivePatientId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("active_patient_id")
                        .HasComputedColumnSql("IF(status = 0, patient_id, NULL)", true);

                    b.Property<DateTime>("BookedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("booked_at_utc");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<long>("SlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("slot_id");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("ix_appt_slot");

                    b.HasIndex("SlotId", "ActivePatientId")
                        .IsUnique()
                        .HasDatabaseName("ux_appt_slot_active_patient");

                    b.HasIndex("PatientId", "Status", "BookedAtUtc")
                        .HasDatabaseName("ix_appt_patient_status");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("MedConnect.Domain.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("specialty");

                    b.HasKey("Id");

                    b.HasIndex("Specialty")
                        .HasDatabaseName("ix_doctors_specialty");

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("MedConnect.Domain.Entities.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("full_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_patients_user");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("MedConnect.Domain.Entities.ScheduleSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BookedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("booked_count");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.ComplexProperty<Dictionary<string, object>>("TimeSlot", "MedConnect.Domain.Entities.ScheduleSlot.TimeSlot#TimeSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("EndUtc")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("end_time_utc");

                            b1.Property<DateTime>("StartUtc")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("start_time_utc");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("schedule_slots", null, t =>
                        {
                            t.HasCheckConstraint("ck_slot_booked", "booked_count >= 0 AND booked_count <= capacity");

                            t.HasCheckConstraint("ck_slot_capacity", "capacity >= 1");

                            t.HasCheckConstraint("ck_slot_time_order", "start_time_utc < end_time_utc");
                        });
                });

            modelBuilder.Entity("MedConnect.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<sbyte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MedConnect.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MedConnect.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appt_patient");

                    b.HasOne("MedConnect.Domain.Entities.ScheduleSlot", null)
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appt_slot");
                });

            modelBuilder.Entity("MedConnect.Domain.Entities.Patient", b =>
                {
                    b.HasOne("MedConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patients_user");
                });

            modelBuilder.Entity("MedConnect.Domain.Entities.ScheduleSlot", b =>
                {
                    b.HasOne("MedConnect.Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_slot_doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
